# Generated by Django 4.1.7 on 2023-05-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=128, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='mail',
            field=models.EmailField(max_length=128, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(null=True, verbose_name='Dni'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(default='1900-01-01', verbose_name='Fecha de nacimiento'),
        ),
    ]
