# Generated by Django 4.1.7 on 2023-05-13 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0002_alter_alumno_apellido_alter_alumno_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleAlumno',
            fields=[
                ('fecha_nacimiento', models.DateField(default='1900-01-01', verbose_name='Fecha de nacimiento')),
                ('fecha_ingreso', models.DateField(default='1900-01-01', verbose_name='Fecha de ingreso al sistema')),
                ('direccion', models.CharField(max_length=256, verbose_name='Dirección')),
                ('mail_alternativo', models.EmailField(max_length=128, verbose_name='Email alternativo')),
                ('titulo', models.BooleanField(verbose_name='Titulo secundario entregado')),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aula_virtual.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=128, verbose_name='Apellido')),
                ('mail', models.EmailField(max_length=128, verbose_name='Email')),
                ('dni', models.IntegerField(null=True, verbose_name='Dni')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_nacimiento',
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.IntegerField(verbose_name='Número de comisión')),
                ('alumnos', models.ManyToManyField(to='aula_virtual.alumno')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.instructor')),
            ],
        ),
    ]
