# Generated by Django 4.1.7 on 2023-05-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0003_detallealumno_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='legajo',
            field=models.CharField(max_length=100, null=True, verbose_name='Legajo'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='cuit',
            field=models.CharField(max_length=100, null=True, verbose_name='Cuit'),
        ),
    ]
